
POST https://localhost:7057/api/user/register HTTP/1.1
Content-Type: application/json

{
  "userName": "kimrenny",
  "email": "qa@gmail.com",
  "password": "1233211@Ab",
  "captchaToken": "03AFcWeA4y1wq4eJNbTne7BkQrBIlGFGSzytypX-SGE8zKpkEJ…HpKb1FVCIZOdJBeujBOjWqXn-Uh6vcTZOPAzdZrd1ThXu7h8Q"
}

###

POST https://localhost:7057/api/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "qa@gmail.com",
  "password": "1233211@Ab",
  "captchaToken": "03AFcWeA4y1wq4eJNbTne7BkQrBIlGFGSzytypX-SGE8zKpkEJ…HpKb1FVCIZOdJBeujBOjWqXn-Uh6vcTZOPAzdZrd1ThXu7h8Q",
  "deviceInfo": {
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "platform": "Win32"
  }
}



###
